import React from 'react';
import { Printer } from 'lucide-react';

type Transaction = {
  id: string;
  type: 'Deposit' | 'Withdrawal';
  asset: string;
  amount: number;
  status: string;
  date: string;
  reference: string;
  fees?: number;
  anchorSignature?: string;
};

interface TransactionReceiptProps {
  transaction: Transaction;
  onPrint?: () => void;
}

export const TransactionReceipt: React.FC<TransactionReceiptProps> = ({ transaction, onPrint }) => {
  const fmtAmount = (n: number) =>
    n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  return (
    <div className="receipt-print">
      <div className="no-print mb-4 flex items-center justify-end">
        <button
          type="button"
          onClick={onPrint}
          className="action-button inline-flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-800/50 px-4 py-2 text-sm font-medium text-slate-200 hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-text"
        >
          <Printer size={16} aria-hidden="true" />
          Print Receipt
        </button>
      </div>

      <div className="glass-card p-6 sm:p-8">
        <div className="mb-6 flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h3 className="font-display text-xl font-bold text-slate-100">Transaction Receipt</h3>
            <p className="text-sm text-slate-400">
              {transaction.type} — {transaction.asset}
            </p>
          </div>
          <span className="inline-flex w-fit items-center rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-emerald-400">
            {transaction.status}
          </span>
        </div>

        <table className="w-full text-left text-sm">
          <tbody className="divide-y divide-slate-700">
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Transaction ID
              </th>
              <td className="py-3 font-mono text-slate-200">{transaction.id}</td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Tx Hash
              </th>
              <td className="py-3 font-mono text-slate-200 break-all">{transaction.reference}</td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Date
              </th>
              <td className="py-3 text-slate-200">
                <time dateTime={transaction.date}>{transaction.date}</time>
              </td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Type
              </th>
              <td className="py-3 text-slate-200">{transaction.type}</td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Asset
              </th>
              <td className="py-3 text-slate-200">{transaction.asset}</td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Amount
              </th>
              <td className="py-3 font-mono text-slate-200">${fmtAmount(transaction.amount)}</td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Fees
              </th>
              <td className="py-3 font-mono text-slate-200">
                {transaction.fees !== undefined ? `$${fmtAmount(transaction.fees)}` : '—'}
              </td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Anchor Signature
              </th>
              <td className="py-3 font-mono text-xs text-slate-400 break-all">
                {transaction.anchorSignature || '—'}
              </td>
            </tr>
          </tbody>
        </table>

        <div className="mt-6 text-xs text-slate-500">
          <p>This receipt was generated by AnchorPoint. For support, contact support@anchorpoint.local.</p>
          <p className="mt-1">Printed on {new Date().toISOString().split('T')[0]}</p>
        </div>
      </div>
    </div>
  );
};

export default TransactionReceipt;
