import React from 'react';
import { Printer, Download, Anchor } from 'lucide-react';

type Transaction = {
  id: string;
  type: 'Deposit' | 'Withdrawal';
  asset: string;
  amount: number;
  status: string;
  date: string;
  reference: string;
  fees?: number;
  anchorSignature?: string;
};

interface TransactionReceiptProps {
  transaction: Transaction;
  onPrint?: () => void;
}

const escapeHtml = (value: string | number): string =>
  String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

export const TransactionReceipt: React.FC<TransactionReceiptProps> = ({ transaction, onPrint }) => {
  const fmtAmount = (n: number) =>
    n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const fees = transaction.fees ?? 0;
  const netAmount = transaction.amount - fees;

  const handlePrint = () => {
    if (onPrint) {
      onPrint();
      return;
    }
    window.print();
  };

  const buildStandaloneReceiptHtml = (): string => {
    const rows = [
      ['Transaction ID', escapeHtml(transaction.id)],
      ['Tx Hash', escapeHtml(transaction.reference)],
      ['Date', escapeHtml(transaction.date)],
      ['Type', escapeHtml(transaction.type)],
      ['Asset', escapeHtml(transaction.asset)],
      ['Amount', `$${fmtAmount(transaction.amount)}`],
      ['Fees', transaction.fees !== undefined ? `$${fmtAmount(transaction.fees)}` : '—'],
      ['Net Amount', `$${fmtAmount(netAmount)}`],
      ['Anchor Signature', transaction.anchorSignature ? escapeHtml(transaction.anchorSignature) : '—'],
      ['Status', escapeHtml(transaction.status)],
    ]
      .map(([label, value]) => `<tr><th>${label}</th><td>${value}</td></tr>`)
      .join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>AnchorPoint Receipt ${escapeHtml(transaction.id)}</title>
  <style>
    body { font-family: Inter, system-ui, sans-serif; color: #0f172a; margin: 40px; }
    .receipt { max-width: 640px; margin: 0 auto; border: 1px solid #cbd5e1; border-radius: 12px; padding: 32px; }
    .stamp { display: inline-flex; align-items: center; gap: 8px; border: 2px solid #0f766e; color: #0f766e; border-radius: 9999px; padding: 4px 14px; font-size: 12px; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; }
    h1 { font-size: 22px; margin: 16px 0 4px; }
    .sub { color: #475569; font-size: 13px; margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th, td { text-align: left; padding: 8px 0; border-bottom: 1px solid #e2e8f0; }
    th { color: #475569; font-weight: 500; width: 40%; }
    td { font-family: ui-monospace, monospace; word-break: break-all; }
    .meta { margin-top: 24px; font-size: 12px; color: #94a3b8; }
  </style>
</head>
<body>
  <div class="receipt">
    <span class="stamp">&#9875; Verified by AnchorPoint</span>
    <h1>Transaction Receipt</h1>
    <p class="sub">${escapeHtml(transaction.type)} &mdash; ${escapeHtml(transaction.asset)}</p>
    <table>
      <tbody>${rows}</tbody>
    </table>
    <p class="meta">This receipt was generated by AnchorPoint. For support, contact support@anchorpoint.local.</p>
    <p class="meta">Printed on ${new Date().toISOString().split('T')[0]}</p>
  </div>
</body>
</html>`;
  };

  const handleSaveReceipt = () => {
    const blob = new Blob([buildStandaloneReceiptHtml()], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AnchorPoint_Receipt_${transaction.id}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="receipt-print" data-testid="transaction-receipt">
      <div className="no-print mb-4 flex items-center justify-end gap-2">
        <button
          type="button"
          onClick={handlePrint}
          className="action-button inline-flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-800/50 px-4 py-2 text-sm font-medium text-slate-200 hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-text"
        >
          <Printer size={16} aria-hidden="true" />
          Print Receipt
        </button>
        <button
          type="button"
          onClick={handleSaveReceipt}
          className="action-button inline-flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-800/50 px-4 py-2 text-sm font-medium text-slate-200 hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-text"
        >
          <Download size={16} aria-hidden="true" />
          Save Receipt
        </button>
      </div>

      <div className="glass-card p-6 sm:p-8">
        <div className="mb-6 flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <span
              className="mb-2 inline-flex items-center gap-1.5 rounded-full border border-emerald-500/40 px-3 py-1 text-[11px] font-bold uppercase tracking-widest text-emerald-500"
              role="img"
              aria-label="Verified by AnchorPoint"
            >
              <Anchor size={12} aria-hidden="true" />
              Verified by AnchorPoint
            </span>
            <h3 className="font-display text-xl font-bold text-slate-100">Transaction Receipt</h3>
            <p className="text-sm text-slate-400">
              {transaction.type} — {transaction.asset}
            </p>
          </div>
          <span className="inline-flex w-fit items-center rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-emerald-400">
            {transaction.status}
          </span>
        </div>

        <table className="w-full text-left text-sm">
          <tbody className="divide-y divide-slate-700">
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Transaction ID
              </th>
              <td className="py-3 font-mono text-slate-200">{transaction.id}</td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Tx Hash
              </th>
              <td className="py-3 font-mono text-slate-200 break-all">{transaction.reference}</td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Timestamp
              </th>
              <td className="py-3 text-slate-200">
                <time dateTime={transaction.date}>{transaction.date}</time>
              </td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Type
              </th>
              <td className="py-3 text-slate-200">{transaction.type}</td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Asset
              </th>
              <td className="py-3 text-slate-200">{transaction.asset}</td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Amount
              </th>
              <td className="py-3 font-mono text-slate-200">${fmtAmount(transaction.amount)}</td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Fees
              </th>
              <td className="py-3 font-mono text-slate-200">
                {transaction.fees !== undefined ? `$${fmtAmount(transaction.fees)}` : '—'}
              </td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Net Amount
              </th>
              <td className="py-3 font-mono text-slate-200">${fmtAmount(netAmount)}</td>
            </tr>
            <tr>
              <th scope="row" className="py-3 pr-4 font-medium text-slate-400">
                Anchor Signature
              </th>
              <td className="py-3 font-mono text-xs text-slate-400 break-all">
                {transaction.anchorSignature || '—'}
              </td>
            </tr>
          </tbody>
        </table>

        <div className="mt-6 text-xs text-slate-500">
          <p>This receipt was generated by AnchorPoint. For support, contact support@anchorpoint.local.</p>
          <p className="mt-1">Printed on {new Date().toISOString().split('T')[0]}</p>
        </div>
      </div>
    </div>
  );
};

export default TransactionReceipt;
